// Hardcoded product data for demo purposes
const products = [
  {
    id: 1,
    name: "Red T-Shirt",
    price: 19.99,
    description: "A comfortable red t-shirt.",
    category: "Apparel",
    stock: 10,
    images: ["/images/red-shirt.png"],
  },
  {
    id: 2,
    name: "Blue Jeans",
    price: 39.99,
    description: "Classic blue jeans.",
    category: "Apparel",
    stock: 15,
    images: ["/images/blue-jeans.png"],
  },
  {
    id: 3,
    name: "Sneakers",
    price: 59.99,
    description: "Stylish sneakers for everyday wear.",
    category: "Footwear",
    stock: 8,
    images: ["/images/sneakers.png"],
  },
  {
    id: 4,
    name: "Backpack",
    price: 29.99,
    description: "Durable backpack for school or travel.",
    category: "Accessories",
    stock: 12,
    images: ["/images/backpack.png"],
  },
  {
    id: 5,
    name: "Baseball Cap",
    price: 14.99,
    description: "Adjustable baseball cap.",
    category: "Accessories",
    stock: 20,
    images: ["/images/cap.png"],
  },
  {
    id: 6,
    name: "Sunglasses",
    price: 24.99,
    description: "UV-protected sunglasses.",
    category: "Accessories",
    stock: 18,
    images: ["/images/sunglasses.png"],
  },
  {
    id: 7,
    name: "White T-Shirt",
    price: 17.99,
    description: "Classic white t-shirt.",
    category: "Apparel",
    stock: 14,
    images: ["/images/white-shirt.png"],
  },
  {
    id: 8,
    name: "Running Shorts",
    price: 22.99,
    description: "Lightweight running shorts.",
    category: "Apparel",
    stock: 9,
    images: ["/images/shorts.png"],
  },
  {
    id: 9,
    name: "Sports Watch",
    price: 49.99,
    description: "Water-resistant sports watch.",
    category: "Accessories",
    stock: 7,
    images: ["/images/watch.png"],
  },
  {
    id: 10,
    name: "Black Hoodie",
    price: 34.99,
    description: "Warm black hoodie.",
    category: "Apparel",
    stock: 11,
    images: ["/images/hoodie.png"],
  },
];

export default products;
